version: '3'
services:

  elasticsearch:
    image: elasticsearch:6.7.1
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.7.1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
